Repository incubation-center/FullStack-Website---Group6, pull requests merged in 2022-08, with the labels that each got.

#2 feat(docker): add automated migration script to docker
  .dockerignore
  .env.sample
  .gitignore
  Dockerfile
  README.md
  components/recipe/createRecipe.tsx
  dev.env.sample
  docker-compose.yml
  package.json
  pages/api/hello.ts
  pages/api/recipe.ts
  pages/api/recipe/create.ts
  pages/index.tsx
  prisma/migrations/20220731112128_create_recipe_test_to_test_connection/migration.sql
  prisma/migrations/20220731133305_/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
Labels: enhancement

#3 feat(lib/prisma): add a global singleton prisma client object
  .gitignore
  lib/prisma.ts
  pages/api/recipe.ts
  pages/api/recipe/create.ts
  prisma/schema.prisma
Labels: enhancement

#6 fix(docker): change docker containers ports
  .env.sample
  Dockerfile
  docker-compose.yml
  package.json
  pages/api/recipe/create.ts
Labels: enhancement

#14 Homepage
  .env.sample
  components/IngredientTabs.js
  components/ingredients-list.js
  dev.env.sample
  pages/index.js
  pages/recipes-result.js
  yarn.lock
Labels: enhancement

#20 Navbar and Footer Refactor
  components/footer.js
  components/navbar.js
Labels: enhancement

#24 Warning: Test run the code first before merge to main (Mobx Setup)
  .babelrc
  package.json
  pages/_app.js
  pages/typescript/_app.tsx
  stores/RecipeStore.js
  tsconfig.json
  yarn.lock
Labels: help wanted

#26 :art: Login && Register Page UI
  package.json
  pages/login.js
  pages/register.js
  tailwind.config.js
  yarn.lock
Labels: enhancement

#37 Bookmark Features
  components/bookmark-card.js
  components/ingredient-tabs.js
  components/recipe-card.js
  pages/_app.js
  pages/bookmarks.js
  pages/cookbooks.js
  pages/recipes-result.js
  stores/BookmarkStore.js
  stores/RecipeStore.js
  styles/globals.css
Labels: enhancement

#43 Fix on Ingredient Checklist
  components/ingredient-list.js
  components/ingredient-tabs.js
  next.config.js
  pages/recipes-result.js
  stores/IngredientStore.js
Labels: bug

#46 feat(db): add recipe, ingredients data, update their m2m schema. automate generate data from json
  README.md
  components/ingredient/deleteIngredient.jsx
  lib/data/all_ingredients.json
  lib/data/all_recipes.json
  pages/api/ingredient/all.js
  pages/api/ingredient/create.js
  pages/api/ingredient/delete.js
  pages/api/ingredient/index.js
  pages/api/recipe/create.js
  pages/s_ingredient.js
  pages/s_readAndAddData.js
  pages/s_recipes.js
  prisma/migrations/20220826200517_/migration.sql
  prisma/schema.prisma
Labels: enhancement
